## CHANGE this to the name of your plugin.
name: FluffyMachines

## CHANGE this to your username.
author: NCBPFluffyBear

## CHANGE this to a meaninful but short description of your plugin.
description: 黏液科技附加 Fluffy機器 繁體翻譯版.

## CHANGE this to the path of the class that extends JavaPlugin.
main: io.ncbpfluffybear.fluffymachines.FluffyMachines

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]
softdepend: [mcMMO, NoCheatPlus]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

commands:
  fluffymachines:
    description: FluffyMachines Command
    usage: /<command>
    aliases: [fm]

permissions:
  fluffymachines.admin:
    description: Allows you to use FluffyMachines admin commands